config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :marks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :post

  validates :points, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :marks, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController

  def create
    @post = Post.find params[:post_id]

    mark = Mark.new marks_params
    mark.letter =
      if mark.points > 85
        'A'
      elsif mark.points > 65
        'B'
      elsif mark.points > 40
        'C'
      elsif mark.points > 20
        'D'
      else
        'F'
      end
    @post.marks.create({ points: mark.points, letter: mark.letter })
    redirect_to post_path @post
  end

  private def marks_params
    params.require(:mark).permit(:points)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'Dev by Me!'
    @body = 'Pavlyuk Alexsandr Petrovich\nIVT-18-2'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to root_path
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  private def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>Reports</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <ul class="navbar-nav">
          <li class="nav-item">
            <span class="navbar-brand"><%= link_to "Home", root_path %></span>
          </li>
          <li class="nav-item">
            <span class="navbar-brand"><%= link_to "About", about_path %></span>
          </li>
          <li class="nav-item">
            <span class="navbar-brand"><%= link_to "New", new_post_path %></span>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container"
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h4><%= @heading %></h4>
<p><%= @body %></p>

app/views/posts/edit.html.erb
<span>Edit report</span>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Title<br>
    <%= f.text_field :title, :class => 'form-control' %>
  </p>
  <p>
    Description<br>
    <%= f.text_area :description, :class => 'form-control' %>
  </p>
  <p>
    <%= f.submit :class => 'btn btn-success' %>
  </p>

<% end %>

app/views/posts/index.html.erb
<h3>All reports</h3>
<% @post.each do |post| %>
  <h3><%= post.title %></h3>
  <p><%= post.description %></p>
  <%= link_to "Open", post_path(post), :class => "btn btn-outline-primary" %>
<% end %>

app/views/posts/new.html.erb
<span>Create new report</span>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Title<br>
    <%= f.text_field :title, :class => 'form-control' %>
  </p>
  <p>
    Description<br>
    <%= f.text_area :description, :class => 'form-control' %>
  </p>
  <p>
    <%= f.submit :class => 'btn btn-success' %>
  </p>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.description %></p>
<%= link_to "Edit", edit_post_path(@post), :class => "btn btn-warning" %>
<%= link_to "Remove", post_path(@post), method: :delete, data: {confirm: "Do you want remove report?"},
            :class => "btn btn-danger" %>
<br>
<h2>Marks</h2>
<% @post.marks.each do |mark| %>
  <h2>Letter: <%= mark.letter %></h2>
  <h3>Points: <%= mark.points %></h3>

<% end %>

<%= form_for([@post, @post.marks.build]) do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <h3>Points: <%= f.text_field :points, :class => 'form-control' %></h3>
  </p>
<!--  <p>-->
<!--    Letter<%#= f.text_area :description, :class => 'form-control' %>-->
<!--  </p>-->
  <p>
    <%= f.submit :class => 'btn btn-success' %>
  </p>

<% end %>